### ISSUE TITLE
[Minor Issue]: Flipped Returns From Native

### ISSUE THREAD

**Issue by xesdoog** [YimMenu-Lua/YimLLS#1]
The returns from the `GET_VEHICLE_MAX_EXHAUST_BONE_COUNT_` native call are flipped. I know it is documented nearly everywhere that the first return is the bone index and the second is a boolean but it's the opposite. Try this in Lua:
```Lua
local count = VEHICLE.GET_VEHICLE_MAX_EXHAUST_BONE_COUNT_() - 1 -- just to eliminate an exhaust bone that's in the engine bay
for i = 0, count do
  local var_1, var_2 = VEHICLE.GET_VEHICLE_EXHAUST_BONE_(self.get_veh(), i, var_1, var_2)
  log.info("var_1: " .. type(var_1))
  log.info("var_2: " .. type(var_2))
  break
end
```
You'll see that var_1 is the boolean and var_2 is the number, ie the bone index.

**Comment by tupoy-ya** [comment]
Check if d87d70271edcc69c8a11052a912e967ab260c85f fixes the issue.

**Comment by xesdoog** [comment]
Yes it does, thanks!
